package com.fiap.sast.github;
import org.springframework.beans.factory.annotation.Value; import org.springframework.stereotype.Component; import java.net.*; import java.net.http.*; import java.nio.file.*; import java.time.Duration; import java.util.*; import java.util.zip.*;
@Component public class GitHubClient { private final HttpClient http=HttpClient.newBuilder().followRedirects(HttpClient.Redirect.NEVER).connectTimeout(Duration.ofSeconds(15)).build(); @Value("${sast.github.token:}") String token; @Value("${sast.github.max-archive-bytes}") long maxArchive; @Value("${sast.github.max-java-files}") int maxFiles; @Value("${sast.github.max-file-bytes}") long maxFile; @Value("${sast.github.max-extracted-bytes}") long maxExtracted;
 public record Snapshot(String owner,String repo,String url,String reference,List<File> files){} public record File(String path,String content){}
 public Snapshot download(String url,String ref){try{var u=validate(url);var parts=u.getPath().substring(1).replaceFirst("\\.git$","").split("/");if(parts.length!=2)throw new IllegalArgumentException("URL de repositório inválida");var api=URI.create("https://api.github.com/repos/"+parts[0]+"/"+parts[1]+"/zipball"+(ref==null||ref.isBlank()?"":"/"+URLEncoder.encode(ref,java.nio.charset.StandardCharsets.UTF_8)));var req=HttpRequest.newBuilder(api).header("Accept","application/vnd.github+json").header("User-Agent","fiap-sast-cp1").header("Authorization",token.isBlank()?"":"Bearer "+token).GET().build();var first=http.send(req,HttpResponse.BodyHandlers.discarding());if(first.statusCode()==404)throw new NoSuchElementException("Repositório ou referência não encontrado");if(first.statusCode()==403||first.statusCode()==429)throw new RateLimitException();if(first.statusCode()!=302)throw new RuntimeException("GitHub indisponível");var location=first.headers().firstValue("Location").orElseThrow();var redirect=URI.create(location);if(!"codeload.github.com".equals(redirect.getHost()))throw new SecurityException("Redirecionamento inválido");var second=http.send(HttpRequest.newBuilder(redirect).header("User-Agent","fiap-sast-cp1").GET().build(),HttpResponse.BodyHandlers.ofByteArray());if(second.body().length>maxArchive)throw new LimitException();return new Snapshot(parts[0],parts[1],url,ref,extract(second.body()));}catch(IllegalArgumentException|NoSuchElementException|RateLimitException|LimitException|SecurityException e){throw e;}catch(Exception e){throw new RuntimeException("Falha ao baixar snapshot",e);}}
 private URI validate(String raw){URI u=URI.create(raw);if(!"https".equals(u.getScheme())||!"github.com".equals(u.getHost())||u.getUserInfo()!=null||u.getPort()!=-1||u.getQuery()!=null||u.getFragment()!=null)throw new IllegalArgumentException("URL de repositório inválida");return u;}
 private List<File> extract(byte[] zip)throws Exception{var out=new ArrayList<File>();long total=0;try(var z=new ZipInputStream(new java.io.ByteArrayInputStream(zip))){for(ZipEntry e;(e=z.getNextEntry())!=null;){String n=e.getName();if(e.isDirectory()||n.contains("..")||n.startsWith("/")||!n.endsWith(".java")||n.matches(".*(^|/)(target|build|out|vendor|node_modules|\\.gradle)/.*"))continue;byte[] b=z.readAllBytes();total+=b.length;if(b.length>maxFile||total>maxExtracted||out.size()>=maxFiles)throw new LimitException();out.add(new File(n,new String(b,java.nio.charset.StandardCharsets.UTF_8)));}}return out;}
 public static class LimitException extends RuntimeException{} public static class RateLimitException extends RuntimeException{}
}
